title: Justine Pile # your name (or website title) here
logo: "/images/profile.jpg" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data scientist with Bachelor's of Information Technology (IT) currently attending UCI Data Analyst Bootcamp, 5+ years working in IT, and 6+ years working in healthcare.
  <br><br>
  <a href="https://www.linkedin.com/in/CactusCoder" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white"></a>
  <a href="https://www.github.com/JustinePile/" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white"></a>
  <br><br><img src="projects/wordcloud_figure.png">

theme: jekyll-theme-minimal
google_analytics: G-T3S6S8J6YS # your Google Analytics tracking ID here

colors:
  crimson: "#900C3F"
