title: Justine Pile # your name (or website title) here
logo: "/images/profile.jpg" # your photo (or logo) here
description:
  > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.github.com/JustinePile/" target="_blank" rel="noopener noreferrer"><img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white"></a>
  <br>
  Database analyst, software engineer, and data scientist with Bachelor's of Information Technology (IT) currently finishing up UC Irvine's Data Analyst Bootcamp, 5+ years working in IT, and 7+ years working in healthcare.
  <img src="projects/wordcloud_figure.png">

theme: jekyll-theme-minimal
google_analytics: G-T3S6S8J6YS # your Google Analytics tracking ID here

colors:
  crimson: "#900C3F"
